# ============================================================================
# mu_test.R
# Test a user cohort (e.g. SAVI, 5 donors) for one gene against the healthy
# atlas baseline, by comparing the two FITTED NB MEAN PARAMETERS (mu):
#
#   * baseline mu : brms zero-inflated NB fit. The NB mean parameter is
#                   mu = exp(linear predictor) = posterior_linpred(transform=FALSE)
#                   exponentiated  (NOT posterior_epred, which for ZINB returns
#                   (1 - zi) * mu, the expected count). Marginalised over the
#                   universal healthy covariate grid -> draws of log(mu).
#   * cohort mu   : edgeR NB fit with a group-means design (~0 + group), with the
#                   offset set to the SAME scale_abundance offset = log(1/multiplier)
#                   the ZINB was trained with (reference sample -> offset 0, so
#                   log(mu) at offset 0 is on the baseline's scale). KEY FINDING:
#                   do NOT read fit$coefficients - edgeR's DGEList pipeline
#                   internally rescales a supplied offset by a constant, so its
#                   coefficients are shifted on the ABSOLUTE scale (the shift
#                   cancels in group-vs-group contrasts but NOT when comparing an
#                   absolute mu to an external baseline, which is what we do). We
#                   take the point estimate from the raw NB MLE (mglmOneGroup with
#                   the offset applied directly) and use glmQLFit only for the
#                   QL-shrunk Wald SE (invariant to a constant offset shift).
#
# Offset equivalence (verified): calcNormFactors(TMMwsp) and scale_abundance(TMMwsp)
# give offsets that are identical up to a global constant (correlation 1), so the
# normalisation is the same; scale_abundance is used only because it re-anchors the
# reference sample to offset 0, matching the brms training convention exactly.
#
# Tests (two nulls; the second is the biomarker-appropriate one):
#   PREDICTION-INTERVAL (conservative): cohort vs the FULL marginal log(mu) spread
#     (welch_t_from_mean_se with se = sd_log_mu, + empirical upper-tail rank).
#     Asks "is the cohort outside the entire cloud of healthy conditions?".
#   DEVIATION-FROM-MEAN (lever a): cohort vs the posterior of the healthy GRAND
#     MEAN (grid collapsed per draw; se = sd_grand_mean << sd_log_mu, + rank).
#     Asks "is the cohort mean shifted from the average healthy mu?".
#   bootstrapping_p_value() - non-parametric KS of observed counts vs the posterior
#     PREDICTIVE draws; kept as a reference but note (see report) that testing on
#     the predicted-count scale conflates NB + zero-inflation sampling noise and is
#     under-powered relative to the mu (linpred) tests above.
#
# Self-contained: loads cached objects built by
#   * mu_test_build_env.R       -> se_monocytic + ref_sample_name
#   * mu_test_epred_baseline.R  -> per-gene log(mu) draws (posterior_linpred) +
#                                  per-draw grand-mean draws
# and the per-gene posterior-predictive draws from the qmd store on disk.
# ============================================================================

suppressMessages({
  library(SummarizedExperiment)
  library(edgeR)
  library(tidybulk)
  library(magrittr)
  library(dplyr)
  library(tidyverse)
})

# ---------------------------------------------------------------------------
# 0. Environment: cohort SummarizedExperiment + healthy baseline draws
# ---------------------------------------------------------------------------

se_cache  <- "/home/a1237163/mu_test_se_monocytic.rds"
data_dir  <- "/home/a1237163/lab/chen/posteriorHCA/dev/SAVI/data"
baseline_draws_rds <- file.path(data_dir, "SAVI_gene_baseline_draws_universal.rds")
epred_baseline_rds <- "/home/a1237163/mu_test_epred_baseline.rds"

if (!exists("se_monocytic") || !exists("ref_sample_name")) {
  .cache <- readRDS(se_cache)
  se_monocytic    <- .cache$se_monocytic
  ref_sample_name <- .cache$ref_sample_name
}

# Posterior PREDICTIVE draws (counts) per gene -> used by the non-parametric test.
gene_baseline_draws_store <- readRDS(baseline_draws_rds)

get_baseline_for_gene <- function(gene_id) {
  row <- gene_baseline_draws_store[gene_baseline_draws_store$.feature == gene_id, ]
  if (!nrow(row)) stop("No predictive baseline draws stored for gene ", gene_id)
  y_rep <- row$counts_scaled[[1L]]
  list(y_rep = y_rep, n_draws = length(y_rep))
}

# NB MEAN PARAMETER mu draws (log scale) per gene -> used by the parametric test.
# Generated by mu_test_epred_baseline.R via posterior_linpred(transform = FALSE).
get_mu_baseline_for_gene <- function(gene_id) {
  if (!file.exists(epred_baseline_rds)) {
    stop("Missing mu baseline cache. Run mu_test_epred_baseline.R first.")
  }
  ep <- readRDS(epred_baseline_rds)
  if (!identical(ep$gene_id, gene_id)) {
    stop("Cached mu baseline is for ", ep$gene_id, ", not ", gene_id,
         ". Re-run mu_test_epred_baseline.R for this gene.")
  }
  list(
    log_mu      = ep$log_mu,
    mean_log_mu = ep$mean_log_mu,
    sd_log_mu   = ep$sd_log_mu,   # universal/marginal SD = healthy mu heterogeneity
    median_mu   = ep$median_mu,
    n_draws     = ep$n_draws,
    # Lever (a): posterior of the healthy GRAND MEAN (grid collapsed per draw).
    # sd_grand_mean << sd_log_mu: uncertainty in the mean, not the spread.
    grand_mean_draws = ep$grand_mean_draws,
    mean_grand_mean  = ep$mean_grand_mean,
    sd_grand_mean    = ep$sd_grand_mean,
    n_grand          = ep$n_grand
  )
}

# ---------------------------------------------------------------------------
# 1. edgeR NB fit with a group-means design; one fitted mu per group per gene
# ---------------------------------------------------------------------------

# Match the ZINB training scale EXACTLY (see dynamic_tar_script.R): TMMwsp to the
# same reference sample, then offset = log(1 / multiplier). The reference sample
# gets multiplier ~ 1 => offset ~ 0, i.e. the brms `offset = 0` reference scale.
se_test <- se_monocytic |>
  tidybulk::scale_abundance(method = "TMMwsp", reference_sample = ref_sample_name)

counts <- assay(se_test, "counts")
meta   <- as.data.frame(colData(se_test))
offset_vec <- log(1 / meta$multiplier)            # same definition as training

# Category for the SAVI cohorts; the atlas reference column has Category = NA.
group <- as.character(meta$Category)
group[is.na(group)] <- "reference"
meta$group <- factor(group) |> fct_relevel("reference")

dge <- DGEList(counts = counts, samples = meta, genes = as.data.frame(rowData(se_test)))
reference <- which(colnames(dge$counts) == ref_sample_name)

# Use the scale_abundance offset directly (overrides edgeR's lib.size * norm).
dge$offset <- matrix(offset_vec, nrow = nrow(dge), ncol = ncol(dge), byrow = TRUE)

design <- model.matrix(~ 0 + group, data = meta)
colnames(design) <- sub("^group", "", colnames(design))

dge <- estimateDisp(dge, design)
fit <- glmQLFit(dge, design)

# NB dispersion edgeR used for the GLM weights (trended, falling back as needed).
nb_dispersion <- if (!is.null(dge$trended.dispersion)) {
  dge$trended.dispersion
} else if (!is.null(dge$tagwise.dispersion)) {
  dge$tagwise.dispersion
} else {
  rep_len(dge$common.dispersion, nrow(dge))
}

# Fitted NB mean (log scale) for a cohort, evaluated at offset = 0 (the brms
# reference scale, since offset_vec[reference] = log(1/multiplier_ref) = 0).
#
# IMPORTANT: we do NOT read fit$coefficients here. edgeR's DGEList pipeline
# (glmFit/glmQLFit) internally rescales a supplied offset by a constant, so its
# coefficients are shifted on the ABSOLUTE scale (the shift cancels in group-vs-
# group contrasts, but NOT when comparing absolute mu to an external baseline as
# we do here). We therefore take the point estimate from the raw NB MLE
# (mglmOneGroup with the offset applied directly), which gives log(mu) at
# offset 0 exactly, and keep glmQLFit only for the QL-shrunk Wald SE (which a
# constant offset shift does not affect).
edger_log_mu <- function(gene_id, cohort, fit, nb_dispersion, counts, offset_vec) {
  gi <- match(gene_id, rownames(fit))
  if (is.na(gi)) stop("Gene ", gene_id, " not in edgeR fit.")
  if (!cohort %in% colnames(fit$coefficients)) stop("Group ", cohort, " not in design.")

  disp <- nb_dispersion[gi]
  j    <- which(fit$samples$group == cohort)
  # Genuine NB MLE of log(mu) at offset 0 (offset_vec[reference] = 0).
  log_mu <- edgeR::mglmOneGroup(matrix(counts[gi, j], nrow = 1),
                                dispersion = disp, offset = offset_vec[j])

  # QL Wald SE: SE = sqrt(s2.post * (X' W X)^{-1}_kk). Invariant to a constant
  # offset shift, so it is safe to pair with the MLE above.
  mu_all <- fit$fitted.values[gi, ]
  W      <- mu_all / (1 + disp * mu_all)            # NB IRLS working weights
  cov_un <- solve(t(fit$design) %*% (W * fit$design))
  se     <- sqrt(fit$s2.post[gi] * cov_un[cohort, cohort])

  list(
    log_mu = unname(log_mu),                        # mu at reference depth (log)
    se     = unname(se),
    df     = unname(fit$df.residual.adj[gi])
  )
}

# ---------------------------------------------------------------------------
# 2. Tests
# ---------------------------------------------------------------------------

# Parametric: Welch t-test from two (mean, SE, n) summaries.
welch_t_from_mean_se <- function(mean1, se1, n1, mean2, se2, n2) {
  sd1 <- se1 * sqrt(n1)
  sd2 <- se2 * sqrt(n2)
  se_diff <- sqrt(se1^2 + se2^2)
  t_stat  <- (mean1 - mean2) / se_diff
  df <- (sd1^2 / n1 + sd2^2 / n2)^2 /
    ((sd1^2 / n1)^2 / (n1 - 1) + (sd2^2 / n2)^2 / (n2 - 1))
  p_value <- 2 * pt(abs(t_stat), df = df, lower.tail = FALSE)
  data.frame(
    mean1 = mean1, mean2 = mean2, mean_diff = mean1 - mean2,
    se_diff = se_diff, t = t_stat, df = df, p_value = p_value
  )
}

# Non-parametric: bootstrap the chosen metric (default KS) of observed values
# vs the baseline draws, against a null built by resampling the draws.
# focal_draws are the baseline values at the quantile positions matching the
# observed sample (deterministic, representative reference); the bootstrap null
# resamples the full baseline to calibrate the statistic.
bootstrapping_p_value <-
  function(obs, draws, n_bootstrap = 1000, seed = NULL,
           metric = "ks.test", alternative = "greater", detail = FALSE) {
    if (!is.null(seed)) set.seed(seed)
    draws <- sort(draws)
    draws.p <- (1:length(draws) - 0.5) / length(draws)
    obs.p <- (1:length(obs) - 0.5) / length(obs)
    focal_draws <- draws[sapply(obs.p, function(x) which.min(abs(x - draws.p)))]
    bootstrap_draws <- lapply(1:n_bootstrap, function(i) {
      sample(draws, length(obs), replace = TRUE)
    })
    focal_metric <- do.call(metric, list(obs, focal_draws))$statistic
    bootstrap_metric <- sapply(bootstrap_draws, function(x) {
      do.call(metric, list(focal_draws, x))$statistic
    })
    p_val_raw <- (
      sum(focal_metric < bootstrap_metric) +
        sum(focal_metric == bootstrap_metric) / 2
    ) / length(bootstrap_metric)
    p_vals <- c(greater = p_val_raw,
                less = 1 - p_val_raw,
                two.sided = 2 * min(p_val_raw, 1 - p_val_raw))
    if (detail) {
      return(list(p.value = p_vals,
                  focal_metric = focal_metric,
                  bootstrap_metric = bootstrap_metric,
                  focal_draws = focal_draws,
                  bootstrap_draws = bootstrap_draws))
    }
    unname(p_vals[alternative])
  }

# Per-gene, per-cohort driver.
test_gene_cohort <- function(gene_id, cohort, fit, se,
                             baseline = NULL, mu_baseline = NULL,
                             nb_dispersion, counts, offset_vec,
                             metric = "ks.test", alternative = "greater",
                             n_bootstrap = 1000, seed = 1) {
  if (is.null(baseline))    baseline    <- get_baseline_for_gene(gene_id)
  if (is.null(mu_baseline)) mu_baseline <- get_mu_baseline_for_gene(gene_id)

  # edgeR cohort mu (one fitted NB mean + SE), on the log scale at ref depth.
  cm <- edger_log_mu(gene_id, cohort, fit, nb_dispersion, counts, offset_vec)

  # Parametric test on log(mu): cohort estimate vs the baseline mu distribution.
  # se1 = baseline SD = healthy mu heterogeneity (universal baseline); the
  # baseline mean is treated as well-determined (n1 = n_draws).
  welch <- welch_t_from_mean_se(
    mean1 = mu_baseline$mean_log_mu, se1 = mu_baseline$sd_log_mu,
    n1    = mu_baseline$n_draws,
    mean2 = cm$log_mu, se2 = cm$se, n2 = cm$df + 1
  )

  # Robust complement: where does the cohort log(mu) fall in the baseline draws?
  emp_p_upper <- mean(mu_baseline$log_mu >= cm$log_mu)

  # Lever (a) — deviation from the healthy MEAN (credible, not prediction).
  # Parametric: se1 = SD of the grand-mean draws = SE of the healthy mean.
  welch_mean <- welch_t_from_mean_se(
    mean1 = mu_baseline$mean_grand_mean, se1 = mu_baseline$sd_grand_mean,
    n1    = mu_baseline$n_grand,
    mean2 = cm$log_mu, se2 = cm$se, n2 = cm$df + 1
  )
  # Non-parametric: rank the cohort log(mu) within the grand-mean posterior.
  emp_p_mean_upper <- mean(mu_baseline$grand_mean_draws >= cm$log_mu)
  emp_p_mean_two   <- 2 * min(emp_p_mean_upper, 1 - emp_p_mean_upper)

  # Non-parametric bootstrap (rank-based KS) on the natural count scale.
  samples <- rownames(fit$samples)[which(fit$samples$group == cohort)]
  obs <- assay(se[gene_id, samples], "counts")[1, ]
  boot_p <- bootstrapping_p_value(
    obs, baseline$y_rep, n_bootstrap = n_bootstrap, seed = seed,
    metric = metric, alternative = alternative
  )

  list(
    gene_id       = gene_id,
    cohort        = cohort,
    cohort_log_mu = cm$log_mu,
    cohort_mu     = exp(cm$log_mu),
    cohort_se     = cm$se,
    welch         = cbind(cohort = cohort, welch),
    emp_p_upper   = emp_p_upper,
    welch_mean       = cbind(cohort = cohort, welch_mean),
    emp_p_mean_upper = emp_p_mean_upper,
    emp_p_mean_two   = emp_p_mean_two,
    bootstrap_p   = boot_p
  )
}

# ---------------------------------------------------------------------------
# 3. Run for one gene
# ---------------------------------------------------------------------------

gene_id <- "ENSG00000196428" # TSC22D2

baseline    <- get_baseline_for_gene(gene_id)
mu_baseline <- get_mu_baseline_for_gene(gene_id)

savi <- test_gene_cohort(gene_id, "SAVI", fit, se_test,
                         baseline, mu_baseline, nb_dispersion, counts, offset_vec)
ctrl <- test_gene_cohort(gene_id, "CTRL", fit, se_test,
                         baseline, mu_baseline, nb_dispersion, counts, offset_vec)

cat("\n=== Gene", gene_id, "(TSC22D2) ===\n")
cat(sprintf("baseline mu: median = %.1f | log(mu) mean = %.3f sd = %.3f (n_draws = %d)\n\n",
            mu_baseline$median_mu, mu_baseline$mean_log_mu,
            mu_baseline$sd_log_mu, mu_baseline$n_draws))

cat("edgeR cohort mu @ reference depth:\n")
cat(sprintf("  SAVI: mu = %.1f  log(mu) = %.3f +/- %.3f\n",
            savi$cohort_mu, savi$cohort_log_mu, savi$cohort_se))
cat(sprintf("  CTRL: mu = %.1f  log(mu) = %.3f +/- %.3f\n",
            ctrl$cohort_mu, ctrl$cohort_log_mu, ctrl$cohort_se))

cat(sprintf("baseline mu SD decomposition: prediction (full spread) = %.3f | mean (grand-mean) = %.3f\n",
            mu_baseline$sd_log_mu, mu_baseline$sd_grand_mean))

cat("\n========================  PREDICTION-INTERVAL test (conservative)  ========================\n")
cat("Null: is the cohort outside the ENTIRE cloud of healthy conditions?\n")

cat("\n--- Welch t on log(mu): cohort vs baseline mu distribution ---\n")
print(rbind(savi$welch, ctrl$welch), row.names = FALSE)

cat("\n--- Empirical upper-tail P(baseline log(mu) >= cohort log(mu)) ---\n")
cat(sprintf("  SAVI: %.4f   CTRL: %.4f\n", savi$emp_p_upper, ctrl$emp_p_upper))

cat("\n========================  [Lever a] DEVIATION-FROM-MEAN test  ========================\n")
cat("Null: is the cohort mean shifted from the AVERAGE healthy mu? (biomarker question)\n")

cat("\n--- Welch t on log(mu): cohort vs healthy grand-mean posterior ---\n")
print(rbind(savi$welch_mean, ctrl$welch_mean), row.names = FALSE)

cat("\n--- Non-parametric: P(grand-mean draw >= cohort log(mu)) ---\n")
cat(sprintf("  SAVI: upper = %.4f  two-sided = %.4f\n", savi$emp_p_mean_upper, savi$emp_p_mean_two))
cat(sprintf("  CTRL: upper = %.4f  two-sided = %.4f\n", ctrl$emp_p_mean_upper, ctrl$emp_p_mean_two))

cat("\n--- Bootstrap KS p-value (observed counts vs baseline predictive draws) ---\n")
cat(sprintf("  SAVI: %.4g   CTRL: %.4g\n", savi$bootstrap_p, ctrl$bootstrap_p))
